Port some changes in develop to humble-devel
sbgisen/brass_gazebo_battery pull request #14
Opened 2024-02-15 03:29 UTC by Tacha-S

## Summary

以下の変更をhumble-develにも適用
- #12 
- #13

- fix #

## Detail

## Impact

## Test

  

## Attention

2024-02-19 10:07 UTC, h-wata approved these changes, later dismissed
この中身としては問題ないのですが、cubeリポジトリの方では`cube_gazebo/scripts/battery_charging_simulation.py`のService定義を変える必要がありました。


```
diff --git a/cube_gazebo/scripts/battery_charging_simulation.py b/cube_gazebo/scripts/battery_charging_simulation.py
index 229df86..224d04a 100755
--- a/cube_gazebo/scripts/battery_charging_simulation.py
+++ b/cube_gazebo/scripts/battery_charging_simulation.py
@@ -20,7 +20,7 @@ import sys
 import threading

 import rclpy
-from brass_gazebo_battery.srv import SetCharging
+from std_srvs.srv import SetBool
 from rclpy.executors import ExternalShutdownException
 from rclpy.node import Node
 from std_msgs.msg import Float32
@@ -44,7 +44,7 @@ class BatteryChargingSimulation(Node):
         self.brass_battery_service_name = self.get_parameter('set_charging').value
         self.voltage_threshold = self.get_parameter('voltage_threshold').value

-        self.client = self.create_client(SetCharging, self.brass_battery_service_name)
+        self.client = self.create_client(SetBool, self.brass_battery_service_name)

         # Start Subscriber
         self.create_subscription(Float32, 'docking_station_voltage_in', self.voltage_subscriber_callback, 10)
@@ -73,7 +73,7 @@ class BatteryChargingSimulation(Node):
             throttle_duration_sec=1)
         self.docking_flag = bool(data.data > self.voltage_threshold)

-    def set_charging_client(self, charging_flag: bool = True) -> SetCharging.Response:
+    def set_charging_client(self, charging_flag: bool = True) -> SetBool.Response:
         """Call set_charging service.

         Args:
@@ -84,11 +84,11 @@ class BatteryChargingSimulation(Node):
         """
         self.client.wait_for_service()
         try:
-            service_result = self.client.call(SetCharging.Request(charging=charging_flag))
+            service_result = self.client.call(SetBool.Request(data=charging_flag))
             return service_result
         except TypeError as err:
             self.get_logger().error('Service call failed: %s' % err)
-        return SetCharging.Response()
+        return SetBool.Response()
```

2024-02-19 10:10 UTC, h-wata commented
単純に興味ですが、SOARでは`battery_charging_simulation.py`などなくても充電の挙動を実現できてるのでしょうか？

2024-02-19 10:55 UTC, jsupratman13 commented
> 単純に興味ですが、SOARでは`battery_charging_simulation.py`などなくても充電の挙動を実現できてるのでしょうか？ （それであればそちらに合わせたいなと思いました）

SOARは充電ステーションのgazebo pluginを使って充電を再現しています． https://github.com/sbgisen/sbgisen_gazebo_plugins/pull/18 
いずれかcuboidくんもこちらに以降した方がいいと思います．

2024-02-19 11:35 UTC, h-wata commented
なるほど！見落としていました。ありがとうございます😊

2024-02-19 23:53 UTC, Tacha-S commented
cubeもnoeticではgazebo plugin使うようにしてましたが( https://github.com/sbgisen/cube/pull/886 )、humbleだとその変更取り込んでないので後でPR出しておきます。

2024-02-20 01:01 UTC, h-wata commented
ほかコメントなければMergeしたいと思います。

2024-02-20 01:20 UTC, jsupratman13 commented
> ほかコメントなければMergeしたいと思います。

自分の環境だと https://github.com/sbgisen/sbgisen_gazebo_plugins/issues/19 の問題でこのPRの充電部分の動作確認ができない状況 (その他はok) ですが， @h-wata 側で動作確認取れていましたらマージしても大丈夫です．

2024-02-20 01:23 UTC, h-wata commented
https://github.com/sbgisen/cube/pull/886 のMerge後は充電の動作も確認できました。

2024-02-20 02:04 UTC, jsupratman13 requested changes

2024-02-20 02:04 UTC, jsupratman13 commented on src/battery_discharge.cpp
> +  battery_state_msg.current = this->ismooth;
充電中電流が下がり、放電中電流が上がる挙動になっていますがこれ正しいですか？

2024-02-20 02:16 UTC, Tacha-S commented on src/battery_discharge.cpp
> +  battery_state_msg.current = this->ismooth;
バグですね
noeticの方も同様になっているので両方修正します。

2024-02-20 02:24 UTC, Tacha-S commented on src/battery_discharge.cpp
> +  battery_state_msg.current = this->ismooth;
放電中は負の値( `-this->ismooth` )になるようにし、充電中はcharge_currentのtopicと同値になるようにしました

2024-02-20 07:24 UTC, jsupratman13 approved these changes

2024-02-20 07:24 UTC, merged